import { sql } from "drizzle-orm";
import {
  index,
  integer,
  sqliteTable,
  text,
  uniqueIndex,
  type AnySQLiteColumn,
} from "drizzle-orm/sqlite-core";
import type { Insight } from "@/lib/types";

/**
 * Conventions (mirrors src/lib/types.ts, which is the frozen contract):
 * - money is an INTEGER in minor units (cents); negative = outflow, positive = inflow
 * - dates are TEXT: ISO date (YYYY-MM-DD) for ledger dates, ISO datetime for audit stamps
 * - periods/months are TEXT YYYY-MM
 * - ids are TEXT, generated by `id()` in app code
 */

export const users = sqliteTable(
  "users",
  {
    id: text("id").primaryKey(),
    username: text("username").notNull(),
    passwordHash: text("password_hash").notNull(),
    /** bumped on logout and password change; sessions carry it and are rejected
     *  once it moves, which is what makes a stateless JWT revocable */
    sessionVersion: integer("session_version").notNull().default(1),
    createdAt: text("created_at").notNull(),
  },
  (t) => [uniqueIndex("users_username_uq").on(t.username)],
);

export const connections = sqliteTable(
  "connections",
  {
    id: text("id").primaryKey(),
    provider: text("provider", {
      enum: ["plaid", "simplefin", "teller", "manual"],
    }).notNull(),
    institution: text("institution"),
    status: text("status", { enum: ["ok", "error", "reauth_required"] })
      .notNull()
      .default("ok"),
    /** AES-256-GCM blob written by Lane B; never leaves the server */
    credentialsEnc: text("credentials_enc"),
    /** opaque provider cursor persisted between syncs */
    syncCursor: text("sync_cursor"),
    lastSyncAt: text("last_sync_at"),
    lastError: text("last_error"),
    createdAt: text("created_at").notNull(),
  },
  (t) => [index("connections_provider_idx").on(t.provider)],
);

export const accounts = sqliteTable(
  "accounts",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    officialName: text("official_name"),
    type: text("type", {
      enum: [
        "checking",
        "savings",
        "credit",
        "investment",
        "loan",
        "cash",
        "other",
      ],
    }).notNull(),
    currency: text("currency").notNull().default("USD"),
    balance: integer("balance").notNull().default(0),
    available: integer("available"),
    institution: text("institution"),
    connectionId: text("connection_id").references(() => connections.id, {
      onDelete: "set null",
    }),
    /** provider-native account id; not part of the Account contract but required to
     *  make provider syncs idempotent (see repos/accounts.findByExternalId) */
    externalId: text("external_id"),
    mask: text("mask"),
    archived: integer("archived", { mode: "boolean" }).notNull().default(false),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (t) => [
    uniqueIndex("accounts_connection_external_uq").on(
      t.connectionId,
      t.externalId,
    ),
    index("accounts_connection_idx").on(t.connectionId),
    index("accounts_type_idx").on(t.type),
  ],
);

export const categories = sqliteTable(
  "categories",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    parentId: text("parent_id").references((): AnySQLiteColumn => categories.id, {
      onDelete: "set null",
    }),
    /** lucide icon name */
    icon: text("icon"),
    discretionary: integer("discretionary", { mode: "boolean" })
      .notNull()
      .default(false),
    system: integer("system", { mode: "boolean" }).notNull().default(false),
  },
  (t) => [
    index("categories_parent_idx").on(t.parentId),
    uniqueIndex("categories_parent_name_uq").on(t.parentId, t.name),
  ],
);

export const recurringSeries = sqliteTable(
  "recurring_series",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    merchant: text("merchant"),
    /** normalized merchant/name key used to re-identify a series across detections */
    normalizedKey: text("normalized_key").notNull(),
    /** average amount in minor units (signed, same convention as transactions) */
    amount: integer("amount").notNull(),
    cadence: text("cadence", {
      enum: ["weekly", "biweekly", "monthly", "quarterly", "yearly"],
    }).notNull(),
    firstDate: text("first_date").notNull(),
    lastDate: text("last_date").notNull(),
    nextExpectedDate: text("next_expected_date").notNull(),
    occurrences: integer("occurrences").notNull().default(0),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    categoryId: text("category_id").references(() => categories.id, {
      onDelete: "set null",
    }),
    active: integer("active", { mode: "boolean" }).notNull().default(true),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (t) => [
    uniqueIndex("recurring_account_key_uq").on(t.accountId, t.normalizedKey),
    index("recurring_active_idx").on(t.active),
  ],
);

export const transactions = sqliteTable(
  "transactions",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    externalId: text("external_id"),
    /** minor units; negative = outflow, positive = inflow */
    amount: integer("amount").notNull(),
    currency: text("currency").notNull().default("USD"),
    /** ISO date (YYYY-MM-DD) */
    date: text("date").notNull(),
    name: text("name").notNull(),
    merchant: text("merchant"),
    categoryId: text("category_id").references(() => categories.id, {
      onDelete: "set null",
    }),
    /** 'user' freezes the category against the rules engine forever */
    categorySource: text("category_source", { enum: ["auto", "user"] }),
    pending: integer("pending", { mode: "boolean" }).notNull().default(false),
    notes: text("notes"),
    recurringSeriesId: text("recurring_series_id").references(
      () => recurringSeries.id,
      { onDelete: "set null" },
    ),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (t) => [
    /** provider dedup key; accounts are scoped to a connection so this is
     *  "externalId unique per connection". NULLs stay distinct in SQLite, so
     *  manual entries are unaffected. */
    uniqueIndex("transactions_account_external_uq").on(t.accountId, t.externalId),
    index("transactions_account_date_idx").on(t.accountId, t.date),
    index("transactions_date_idx").on(t.date),
    index("transactions_category_date_idx").on(t.categoryId, t.date),
    index("transactions_merchant_idx").on(t.merchant),
    index("transactions_series_idx").on(t.recurringSeriesId),
  ],
);

export const budgets = sqliteTable(
  "budgets",
  {
    id: text("id").primaryKey(),
    categoryId: text("category_id")
      .notNull()
      .references(() => categories.id, { onDelete: "cascade" }),
    /** YYYY-MM */
    month: text("month").notNull(),
    /** limit in minor units, always positive */
    amount: integer("amount").notNull(),
    createdAt: text("created_at").notNull(),
  },
  (t) => [
    uniqueIndex("budgets_category_month_uq").on(t.categoryId, t.month),
    index("budgets_month_idx").on(t.month),
  ],
);

export const insights = sqliteTable(
  "insights",
  {
    id: text("id").primaryKey(),
    kind: text("kind", {
      enum: [
        "category_spike",
        "new_subscription",
        "unused_subscription",
        "budget_breach_forecast",
        "savings_rate",
        "cash_runway",
        "large_transaction",
        "duplicate_charge",
      ],
    }).notNull(),
    severity: text("severity", { enum: ["info", "warn", "critical"] }).notNull(),
    title: text("title").notNull(),
    body: text("body").notNull(),
    action: text("action"),
    refs: text("refs", { mode: "json" })
      .$type<Insight["refs"]>()
      .notNull()
      .default(sql`'{}'`),
    /** YYYY-MM */
    period: text("period").notNull(),
    /** stable per-rule identity so re-running the engine updates instead of duplicating */
    dedupeKey: text("dedupe_key").notNull(),
    dismissed: integer("dismissed", { mode: "boolean" })
      .notNull()
      .default(false),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull(),
  },
  (t) => [
    uniqueIndex("insights_period_kind_key_uq").on(t.period, t.kind, t.dedupeKey),
    index("insights_period_idx").on(t.period),
  ],
);

export const networthSnapshots = sqliteTable(
  "networth_snapshots",
  {
    id: text("id").primaryKey(),
    /** ISO date (YYYY-MM-DD) */
    date: text("date").notNull(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    /** account type captured at snapshot time so history survives re-typing */
    accountType: text("account_type", {
      enum: [
        "checking",
        "savings",
        "credit",
        "investment",
        "loan",
        "cash",
        "other",
      ],
    }).notNull(),
    balance: integer("balance").notNull(),
    currency: text("currency").notNull().default("USD"),
    createdAt: text("created_at").notNull(),
  },
  (t) => [
    uniqueIndex("networth_date_account_uq").on(t.date, t.accountId),
    index("networth_date_idx").on(t.date),
  ],
);

export type UserRow = typeof users.$inferSelect;
export type AccountRow = typeof accounts.$inferSelect;
export type TransactionRow = typeof transactions.$inferSelect;
export type CategoryRow = typeof categories.$inferSelect;
export type BudgetRow = typeof budgets.$inferSelect;
export type ConnectionRow = typeof connections.$inferSelect;
export type InsightRow = typeof insights.$inferSelect;
export type RecurringSeriesRow = typeof recurringSeries.$inferSelect;
export type NetworthSnapshotRow = typeof networthSnapshots.$inferSelect;
